[client]
toolbarMode = "minimal"

[runner]
fastReruns = false
runOnSave = true

[server]
maxMessageSize = 1000

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
